//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSData;

struct _BOMBom;
struct _BOMFSObject;

@interface PKBOM : NSObject
{
    NSData *_bomData;
    struct _BOMBom *_BOMBom;
}

+ (BOOL)_setAttributes:(id)arg1 ofBOMFSObject:(struct _BOMFSObject *)arg2;
+ (id)_attributesOfBOMFSObject:(struct _BOMFSObject *)arg1;
+ (id)_NSFileTypeFromBOMFSObjType:(int)arg1;
- (unsigned long long)totalSize;
- (unsigned long long)fileCount;
- (id)subpathsOfDirectoryAtPath:(id)arg1;
- (id)directoryEnumerator;
- (id)attributesOfItemAtPath:(id)arg1;
- (struct _BOMBom *)BOMBom;
- (void)dealloc;
- (id)initWithBOMData:(id)arg1;
- (id)initWithBOMPath:(id)arg1;

@end

