//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface PKBundleComponentVersion : NSObject
{
    NSString *_shortVersionString;
    NSString *_origShortVersionString;
    NSString *_bundleVersion;
    NSString *_origBundleVersion;
    NSString *_sourceVersion;
    NSString *_buildVersion;
    BOOL _isOnDisk;
}

+ (id)_orderedVersionKeys;
+ (id)_standardizedTupleVersionString:(id)arg1;
+ (id)_combinedVersionAndInfoDictionaryForCFBundle:(struct __CFBundle *)arg1;
+ (id)_combinedVersionAndInfoDictionaryForBundle:(id)arg1;
+ (id)bundleComponentVersionWithOnDiskCFBundle:(struct __CFBundle *)arg1;
+ (id)bundleComponentVersionWithOnDiskBundle:(id)arg1;
+ (id)bundleComponentVersionWithPackageAttributes:(id)arg1;
+ (BOOL)_checksBuildVersion;
@property(readonly) NSString *combinedVersionString;
@property(readonly) NSDictionary *attributeDictionary;
- (BOOL)_isOnDiskComponent;
@property(readonly) NSString *buildVersion;
@property(readonly) NSString *sourceVersion;
@property(readonly) NSString *bundleVersion;
@property(readonly) NSString *shortVersionString;
- (long long)compare:(id)arg1;
- (id)description;
- (void)dealloc;
- (id)initWithAttributes:(id)arg1 forOnDiskComponent:(BOOL)arg2;
- (id)initWithShortVersionString:(id)arg1 bundleVersion:(id)arg2 sourceVersion:(id)arg3 buildVersion:(id)arg4 forOnDiskComponent:(BOOL)arg5;

@end

