//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSString;

@interface PKInstallHistory : NSObject
{
    NSString *_path;
}

+ (id)defaultHistory;
+ (id)historyOnVolume:(id)arg1;
- (id)installedItems;
- (BOOL)addInstallRequest:(id)arg1;
- (void)dealloc;
- (id)initWithPath:(id)arg1;

@end

