//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled May 21 2020 17:01:39).
//
//  Copyright (C) 1997-2019 Steve Nygard.
//

@class NSArray, NSDictionary, NSString, NSURL, PKArchive, PKPackageInfo;

@interface PKPackage : NSObject <NSCoding, NSCopying>
{
    NSURL *_url;
    NSDictionary *_options;
    PKArchive *_archive;
    PKPackageInfo *_packageInfo;
    NSDictionary *_componentMap;
    NSArray *_firmwareBundleComponents;
    BOOL _populatedSubpaths;
}

+ (id)packageWithURL:(id)arg1 options:(id)arg2;
+ (id)packageWithURL:(id)arg1;
+ (id)packageWithPath:(id)arg1 options:(id)arg2;
+ (id)packageWithPath:(id)arg1;
+ (id)_allPackageClasses;
+ (BOOL)canInitWithURL:(id)arg1;
- (void)enumerateBundleComponentsUsingBlock:(id)arg1;
- (void)_populateComponentSubpaths;
@property(readonly) NSURL *fileURL;
@property(readonly) PKArchive *archive;
- (BOOL)extractFilesForBundleComponent:(id)arg1 toPath:(id)arg2 error:(id *)arg3;
- (id)firmwareComponents;
- (id)subpathsForComponent:(id)arg1;
- (id)componentForIdentifier:(id)arg1;
- (id)components;
- (id)_componentMap;
- (id)directoryEnumerator;
- (id)payloadExtractorWithDestination:(id)arg1 externalRoot:(id)arg2 error:(id *)arg3;
- (id)scriptsExtractorWithDestination:(id)arg1 error:(id *)arg2;
@property(readonly) NSString *scriptsSubpath;
- (id)_scriptsDirectory;
@property(readonly) PKPackageInfo *packageInfo;
@property(readonly) NSString *packageVersion;
@property(readonly) NSString *packageIdentifier;
- (BOOL)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)_staticObsoleteFilesOrRecursiveDirectories;
- (id)_staticObsoleteDirectories;
- (id)_staticObsoleteFiles;
- (id)BOMData;
- (id)initWithURL:(id)arg1 options:(id)arg2;
- (id)firmwareComponentsOfType:(long long)arg1;

@end

